### ISSUE TITLE
Commercial third-party library can be replaced?

### ISSUE THREAD

**Issue by everton-sales-branco** [landgraf-dev/aws-sdk-delphi#4]
This is a great library, too bad it depends on the TMS Business components.

**Comment by wlandgraf** [comment]
That's why it's a great library. ;-)

**Comment by omonien** [comment]
I love Porsches. But their price tag is too high. Can’t you remove the engine, the alloy wheels to make it affordable?

:-D

Mit freundlichen Grüßen / Regards
Olaf Monien
CEO Unternehmensberatung Monien
Embarcadero MVP • Coordinator DACH

  +49 69 175 548 151 <tel:+49 69 175 548 151>
  ***@***.*** ***@***.***>
  www.developer-experts.net <http://www.developer-experts.net/>
  Saarstr. 2c • 61350 Bad Homburg • Germany <https://maps.google.com/?q=Saarstr.+2c+%E2%80%A2+61350+Bad+Homburg+%E2%80%A2+Germany>
 <https://www.facebook.com/developerexperts>   <https://www.twitter.com/omonien>   <https://www.linkedin.com/in/olafmonien>

**Comment by everton-sales-branco** [comment]
This argument, if it doesn't have undeclared interests, is what makes the Delphi community weaker every day.

**Comment by omonien** [comment]
Apparently you are looking for „free software“. Delphi has never been in that business, iow, it's the wrong tool for you.

Btw. Delphi comes with two other AWS SDK access options:
- CDATA
- Appercept

Both are free to use for Enterprise license holders (some options available for Professional licenses).

Yet, I like Landgraf’s SDK approach better. Probably because I am already using their XData server stack ...


Mit freundlichen Grüßen / Regards
Olaf Monien
CEO Unternehmensberatung Monien
Embarcadero MVP • Coordinator DACH

  +49 69 175 548 151 <tel:+49 69 175 548 151>
  ***@***.*** ***@***.***>
  www.developer-experts.net <http://www.developer-experts.net/>
  Saarstr. 2c • 61350 Bad Homburg • Germany <https://maps.google.com/?q=Saarstr.+2c+%E2%80%A2+61350+Bad+Homburg+%E2%80%A2+Germany>
 <https://www.facebook.com/developerexperts>   <https://www.twitter.com/omonien>   <https://www.linkedin.com/in/olafmonien>

**Comment by everton-sales-branco** [comment]
Thanks, @wlandgraf. My intention was just to highlight an issue that the entire Delphi community could work on to reduce a dependency on a commercial library. And not to denigrate the quality and usefulness of the library.

**Comment by omonien** [comment]
This is just nonsense, sorry.

Wagner is the brain behind the commercial XData and Aurelius frameworks, where TMS Business Core components were developed for.

Now he came up with idea to put some of his free time into an AWS framework, which he offers as a free add on for TMS Business users. So either use his work or not.  


Mit freundlichen Grüßen / Regards
Olaf Monien
CEO Unternehmensberatung Monien
Embarcadero MVP • Coordinator DACH

  +49 69 175 548 151 <tel:+49 69 175 548 151>
  ***@***.*** ***@***.***>
  www.developer-experts.net <http://www.developer-experts.net/>
  Saarstr. 2c • 61350 Bad Homburg • Germany <https://maps.google.com/?q=Saarstr.+2c+%E2%80%A2+61350+Bad+Homburg+%E2%80%A2+Germany>
 <https://www.facebook.com/developerexperts>   <https://www.twitter.com/omonien>   <https://www.linkedin.com/in/olafmonien>
